source DB_PROJECT.sql;
source INSERT_SCRIPT.sql;
source SIMPLE_QUERIES.sql;
source VIEWS.sql;
source TRIGGERS.sql;

UPDATE BOOKING_DETAILS
SET FROM_DT_TIME = TIMESTAMP('2022-01-20 10:00:00')
WHERE AMOUNT = 150;