SELECT * 
FROM CUSTOMER_DETAILS;

SELECT * 
FROM CAR 
WHERE MAKE = 'HONDA';

SELECT NO_OF_PERSON 
FROM CAR_CATEGORY
WHERE CATEGORY_NAME = 'ECONOMY'
AND LATE_FEE_PER_HOUR = 0.9;

SELECT DISCOUNT_CODE, DISCOUNT_NAME 
FROM DISCOUNT_DETAILS;

SELECT * 
FROM DISCOUNT_DETAILS, BOOKING_DETAILS;

SELECT REGISTRATION_NUMBER, CATEGORY_NAME
FROM CAR, CAR_CATEGORY
WHERE CAR_CATEGORY_NAME = CATEGORY_NAME;

SELECT CITY, ZIPCODE
FROM CUSTOMER_DETAILS
WHERE EMAIL_ID LIKE 'm%@gmail.com';

SELECT *
FROM CAR_CATEGORY
WHERE COST_PER_DAY BETWEEN 30 AND 40;

SELECT DISTINCT CITY, FNAME
FROM CUSTOMER_DETAILS
ORDER BY FNAME;

SELECT CATEGORY_NAME, MODEL_YEAR, MODEL_NAME
FROM CAR, CAR_CATEGORY
WHERE (CAR_CATEGORY_NAME, MODEL_YEAR) = (CATEGORY_NAME, 2015);